services:
    admin.articles:
            class: BlogBundle\Admin\ArticlesAdmin
            arguments: [~, BlogBundle\Entity\Articles, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: "Articles", group: "Articles" }

    admin.category:
            class: BlogBundle\Admin\CategoryAdmin
            arguments: [~, BlogBundle\Entity\Category, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: "Category", group: "Articles" }
